let a = require('./instanceRouter.js');
module.exports = {
    'package.json': require('./packageJson.js'),
    'server.js': require('./server.js'),
    'webpack.base.conf.js': require('./webpackBase.js'),
    'webpack.conf.js': require('./webpackConfig.js'),
    'webpack.dll.conf.js': require('./webpackDll.js'),
    'app.js':  require('./app.js'),
    'app.scss':  require('./appScss.js'),
    'app.css':  require('./appScss.css'),
    'build.scss':  require('./build.js'),
    'entry-client.js':  require('./entryClient.js'),
    'index.template.html':  require('./indexTplHtml.js'),
    'config.js': require('./config.js'),
    'moduleEvent.js': require('./moduleEvent.js'),
    'fetch.js': require('./fetch.js'),
    'filters.js': require('./filters.js'),
    'instancePage.js': require('./instancePage.js'),
    'fof.js': require('./fof.js'),
    'mainView.js': require('./mainView.js'),
    'moduleView.js': require('./moduleView.js'),
    'transferView.js': require('./transferView.js'),
    'instanceRouter.js': require('./instanceRouter.js'),
    'indexRouter.js': require('./indexRouter.js'),
    'instanceStore.js': require('./instanceStore.js'),
    'moduleStore.js': require('./moduleStore.js'),
    'indexStore.js': require('./indexStore.js'),
    'utilStore.js': require('./utilStore.js'),
    'lodash.js': require('./lodash.js'),
    'appVue.js': require('./appVue.js'),
    'babelRc.js': require('./babelRc.js'),

    'table.js':  require('./table.js'),
    'tableReadMe.js':  require('./tableReadMe.js'),
    'tableVue.js':  require('./tableVue.js'),
    'grid.js':  require('./grid.js'),

    'list.js':  require('./list.js'),
    'listVue.js':  require('./listVue.js'),

    'searchVue.js':  require('./searchVue.js'),
    'searchSpriteVue.js':  require('./searchSpriteVue.js'),

    'basePage.js':  require('./basePage.js'),

    'frameCss.js':  require('./frameCss.js'),
    'frameVue.js':  require('./frameVue.js'),
    'portalCollapse.js':  require('./portalCollapse.js'),
    'portalCss.js':  require('./portalCss.js'),
    'portalExpand.js':  require('./portalExpand.js'),
    'portalHeader.js':  require('./portalHeader.js'),
    'portalMenu.js':  require('./portalMenu.js'),
    'menusDemo.js':  require('./menusDemo.js')
}