let a = require('./instanceRouter.js');
module.exports = {
    'package.json': require('./packageJson.js'),
    'server.js': require('./server.js'),
    'webpack.base.conf.js': require('./webpackBase.js'),
    'webpack.conf.js': require('./webpackConfig.js'),
    'webpack.dll.conf.js': require('./webpackDll.js'),
    'app.js':  require('./app.js'),
    'app.scss':  require('./appScss.js'),
    'entry-client.js':  require('./entryClient.js'),
    'index.template.html':  require('./indexTplHtml.js'),
    'config.js': require('./config.js'),
    'moduleEvent.js': require('./moduleEvent.js'),
    'fetch.js': require('./fetch.js'),
    'filters.js': require('./filters.js'),
    'instancePage.js': require('./instancePage.js'),
    'fof.js': require('./fof.js'),
    'mainView.js': require('./mainView.js'),
    'moduleView.js': require('./moduleView.js'),
    'transferView.js': require('./transferView.js'),
    'instanceRouter.js': require('./instanceRouter.js'),
    'indexRouter.js': require('./indexRouter.js'),
    'instanceStore.js': require('./instanceStore.js'),
    'moduleStore.js': require('./moduleStore.js'),
    'indexStore.js': require('./indexStore.js'),
    'utilStore.js': require('./utilStore.js'),
    'lodash.js': require('./lodash.js'),
    'appVue.js': require('./appVue.js'),
    'babelRc.js': require('./babelRc.js'),

    'themeRed.js': require('./themeRed.js'),
    'themeBlue.js': require('./themeBlue.js'),
    'themeSrcRed.js': require('./themeSrcRed.js'),
    'themeSrcBlue.js': require('./themeSrcBlue.js'),
    'themeSrcvar.js': require('./themeSrcvar.js'),
    'themeSrcPackage.js': require('./themeSrcPackage.js'),
    'themeSrcReadme.js': require('./themeSrcReadme.js'),
    'gulpfile.js': require('./gulpfile.js'),
}